### ISSUE TITLE
Invalid API key for an european account and LocalEvaluationClient

### ISSUE THREAD

**Issue by ziraco** [amplitude/experiment-jvm-server#21]
Hi! I'm trying to set a LocalEvaluationClient with the auto-assignment option enabled. I'm getting an "Invalid API key " error.

My organization is in Amplitude Europe and I'm configuring the serverUrl property of the client. Could the error be related to the creation of the Amplitude object [ in this line](https://github.com/amplitude/experiment-jvm-server/blob/3a390b2c3858b93e33164e1df958351e02796863/src/main/kotlin/LocalEvaluationClient.kt#L48) and the serverUrl not being passed to it? 🤔 

Thanks in advance!

**Comment by tyiuhc** [comment]
@ziraco Many thanks for raising this issue! You can now configure the serverUrl property of the client in v1.2.7.

**Comment by ziraco** [comment]
Thanks!
